CREATE SCHEMA IF NOT EXISTS dbgtoadmin;
CREATE TABLE IF NOT EXISTS departamentos(
    idDepartamento INT NOT NULL AUTO_INCREMENT,
    descripcion VARCHAR(100) NOT NULL,
    activo TINYINT NOT NULL DEFAULT 1,
    fechaCreacion DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    fechaActualizacion DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    idEmpleado INT NULL DEFAULT 1,
    PRIMARY KEY(idDepartamento)
)
ENGINE = InnoDB